// DO NOT EDIT. This file is generated by Firebase Studio.
// Add this to your .gitignore.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore } from "firebase/firestore";

export const firebaseConfig = {
  "projectId": "studio-7227648350-99b40",
  "appId": "1:87931520084:web:2e189c322a386b649419c1",
  "apiKey": "AIzaSyAAdYOcnrxlwxZWP8qgDjky76CKw3nJKNc",
  "authDomain": "studio-7227648350-99b40.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "87931520084"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
