// DO NOT EDIT. This file is generated by Firebase Studio.
// Add this to your .gitignore.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  // Your web app's Firebase configuration will be populated here by Firebase Studio.
  // If you are seeing this message in your local development environment,
  // you may need to run the `firebase apps:sdkconfig web` command from the Firebase CLI.
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
