# Generated by Django 4.2.27 on 2026-01-17 20:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='brand.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Cost in EGP per unit/meter', max_digits=10)),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('UNIT', 'Unit'), ('KG', 'Kilogram')], default='METER', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='factory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity required per unit of Product', max_digits=10)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected waste (e.g. 5.00 for 5%)', max_digits=5)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factory.bom')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factory.rawmaterial')),
            ],
            options={
                'unique_together': {('bom', 'raw_material')},
            },
        ),
    ]
