# Generated by Django 4.2.27 on 2026-01-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. JOB-2023-001', max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Planned Production Quantity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('QC', 'Quality Control'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('qc_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PASS', 'Pass'), ('REJECT', 'Reject (Waste)'), ('REPAIR', 'Repair Needed')], default='NA', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brand.product')),
            ],
        ),
    ]
