# Generated by Django 4.2.27 on 2026-01-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_order_location_alter_order_status'),
        ('factory', '0002_productionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='brand.order'),
        ),
    ]
