# Generated by Django 6.0.1 on 2026-01-19 00:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_worker_productionlog_workerattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
