# Generated by Django 4.2.27 on 2026-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_materialpurchase_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('QC', 'Quality Control'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
