# Generated by Django 4.2.27 on 2026-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_alter_productionjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
