# Generated by Django 4.2.27 on 2026-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_rawmaterial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
