# Generated by Django 4.2.27 on 2026-01-17 20:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0002_location_order_orderitem_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRANSFER', 'Factory to Brand Transfer'), ('SALE', 'Sales Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('reference_id', models.CharField(help_text='Job ID or Order Number', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overhead_allocation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('factory_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='e.g. 20.00 for 20%', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='brand.product')),
            ],
        ),
    ]
