# Generated by Django 4.2.27 on 2026-01-18 01:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_order_location_alter_order_status'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Rent, Salaries, Sales, Materials', max_length=100),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='date',
            field=models.DateField(default='2024-01-01', help_text='Date of transaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='module',
            field=models.CharField(choices=[('BRAND', 'Brand'), ('FACTORY', 'Factory')], default='BRAND', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.CharField(choices=[('TRANSFER', 'Factory to Brand Transfer'), ('SALE', 'Sales Revenue'), ('EXPENSE', 'Expense'), ('INTERNAL', 'Internal Treasury Transfer')], max_length=20),
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DAILY', 'Daily Treasury (Drawer)'), ('MAIN', 'Main Treasury (Safe)'), ('BANK', 'Bank Account')], default='MAIN', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='brand.location')),
            ],
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.treasury'),
        ),
    ]
