# Generated by Django 4.2.27 on 2026-01-17 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated cost from Factory (Materials + Labor)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
