# Generated by Django 4.2.27 on 2026-01-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_location_order_orderitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
