# Generated by Django 4.2.27 on 2026-01-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_customer_order_amount_paid_order_is_fully_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='brand.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_PRODUCTION', 'Pending Production'), ('PAID', 'Paid'), ('FULFILLED', 'Fulfilled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
