# Generated by Django 4.2.27 on 2026-01-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_order_location_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('SHOWROOM', 'Showroom'), ('ONLINE', 'Online/Virtual'), ('EVENT', 'Event / Pop-up')], max_length=20),
        ),
    ]
