# Generated by Django 4.2.27 on 2026-01-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(help_text='e.g. my-store.myshopify.com', max_length=255)),
                ('access_token', models.CharField(help_text='Admin API Access Token (shpat_...)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
