# Generated by Django 4.2.27 on 2026-01-18 23:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_shopifyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ltv_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime Value', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='sizing_profile',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'top': 'M', 'shoe': '42'}"),
        ),
        migrations.AddField(
            model_name='customer',
            name='style_preferences',
            field=models.TextField(blank=True, help_text="Comma-separated tags e.g. 'Streetwear, Minimalist'"),
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('VVIP', 'VVIP'), ('ELITE', 'Elite')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Store Visit'), ('PURCHASE', 'Purchase'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('staff_member', models.CharField(help_text='Name of staff who interacted', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='brand.customer')),
            ],
        ),
    ]
