# Generated by Django 6.0.1 on 2026-01-19 00:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_customer_birth_date_customer_ltv_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_overhead',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marketing & Ops Overhead per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_profit_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Brand Profit Margin %', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='factory_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Factory Profit Margin %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Factory Sell Price (Materials + Labor + Factory Margin)', max_digits=10),
        ),
    ]
