# Generated by Django 4.2.27 on 2026-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_product_brand_overhead_product_brand_profit_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_PRODUCTION', 'Pending Production'), ('PAID', 'Paid'), ('FULFILLED', 'Fulfilled'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
