# Generated by Django 4.2.27 on 2026-01-21 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Global Order Discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount per line (total)', max_digits=10),
        ),
    ]
