# Generated by Django 4.2.27 on 2026-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Order notes (from POS or Manager)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(choices=[('PENDING', 'Pending/None'), ('BOSTA', 'Bosta'), ('ARAMEX', 'Aramex'), ('MYLERZ', 'Mylerz'), ('MANUAL', 'Private Rep'), ('OTHER', 'Other')], default='PENDING', max_length=20),
        ),
    ]
