# Generated by Django 4.2.27 on 2026-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_order_notes_order_shipping_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='True if stock has been removed'),
        ),
    ]
