# Generated by Django 4.2.27 on 2026-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, help_text='Group Name (e.g. T-Shirt) for variants', max_length=255, null=True),
        ),
    ]
