# Generated by Django 4.2.27 on 2026-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0017_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, help_text='Shopify Image URL', null=True),
        ),
    ]
