# Generated by Django 4.2.27 on 2026-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0018_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity returned by customer'),
        ),
    ]
