# Generated by Django 4.2.27 on 2026-01-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0019_orderitem_returned_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode / EAN', max_length=100, null=True, unique=True),
        ),
    ]
