# Generated by Django 4.2.27 on 2026-02-01 17:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0021_category_product_last_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('BOSTA', 'Bosta'), ('ARAMEX', 'Aramex'), ('QUIGO', 'QuiGo'), ('OTHER', 'Other')], default='QUIGO', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Photo of signed manifest', null=True, upload_to='manifests/')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='detailed_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('PARTIAL_DELIVERY', 'Partial Delivery'), ('REFUSED', 'Refused'), ('LOST', 'Lost')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual cost charged by courier', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='brand.shippingmanifest'),
        ),
    ]
